-- Eliminar tablas en orden inverso a las dependencias
DROP TABLE TEMP_USUARIOS_A_BLOQUEAR;
DROP TABLE ESTUDIANTES_EXAMEN_FINALIZADO;
DROP TABLE HISTORIAL_EXAMENES_CREADOS;
DROP TABLE PREGUNTAS_CON_BAJO_RENDIMIENTO;
DROP TABLE MODIFICACION_PREGUNTAS;
DROP TABLE HISTORIAL_PRESENTACIONES;
DROP TABLE RESPUESTA_ESTUDIANTE;
DROP TABLE PRESENTACION_EXAMEN;
DROP TABLE EXAMEN_PREGUNTA;
DROP TABLE OPCION_RESPUESTA;
DROP TABLE PREGUNTA;
DROP TABLE EXAMEN;
DROP TABLE MATRICULA;
DROP TABLE JORNADA;
DROP TABLE GRUPO;
DROP TABLE TEMA;
DROP TABLE CONTENIDO;
DROP TABLE UNIDAD;
DROP TABLE PLAN_ESTUDIO;
DROP TABLE USUARIO;
DROP TABLE AULA;
DROP TABLE PERIODO_ACADEMICO;
DROP TABLE CURSO;
DROP TABLE PROGRAMA;
DROP TABLE FACULTAD;
DROP TABLE CATEGORIA_EXAMEN;
DROP TABLE NIVEL_DIFICULTAD;
DROP TABLE TIPO_PREGUNTA;
DROP TABLE TIPO_USUARIO;
DROP TABLE ESTADO_GENERAL;
DROP TABLE AUDITORIA;
DROP TABLE NOTIFICACION;

DROP TABLE USUARIO;
DROP TABLE ESTADO_GENERAL;
DROP TABLE TIPO_USUARIO;

COMMIT;

-- Verificar que no queden tablas
SELECT TABLE_NAME 
FROM USER_TABLES 
ORDER BY TABLE_NAME; 