-- Archivo de secuencias para el proyecto Exami

-- Secuencia para la tabla USUARIO
CREATE SEQUENCE SEQ_ID_USUARIO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Secuencia para la tabla EXAMEN
CREATE SEQUENCE SEQ_ID_EXAMEN START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Secuencia para la tabla PREGUNTA
CREATE SEQUENCE SEQ_ID_PREGUNTA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Secuencia para la tabla OPCION_RESPUESTA
CREATE SEQUENCE SEQ_ID_OPCION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Secuencia para la tabla EXAMEN_PREGUNTA
CREATE SEQUENCE SEQ_ID_EXAMEN_PREGUNTA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Secuencia para la tabla PRESENTACION_EXAMEN
CREATE SEQUENCE SEQ_ID_PRESENTACION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Secuencia para la tabla RESPUESTA_ESTUDIANTE
CREATE SEQUENCE SEQ_ID_RESPUESTA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Secuencia para la tabla AUDITORIA
CREATE SEQUENCE SEQ_ID_AUDITORIA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Secuencia para la tabla NOTIFICACION
CREATE SEQUENCE SEQ_ID_NOTIFICACION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Secuencia para la tabla TEMA
CREATE SEQUENCE SEQ_ID_TEMA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Secuencia para la tabla CATEGORIA_EXAMEN
CREATE SEQUENCE SEQ_ID_CATEGORIA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Secuencia para la tabla ESTADO_GENERAL
CREATE SEQUENCE SEQ_ID_ESTADO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Secuencia para la tabla TIPO_USUARIO
CREATE SEQUENCE SEQ_ID_TIPO_USUARIO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Secuencia para la tabla NIVEL_DIFICULTAD
CREATE SEQUENCE SEQ_ID_NIVEL_DIFICULTAD START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Secuencia para la tabla TIPO_PREGUNTA
CREATE SEQUENCE SEQ_ID_TIPO_PREGUNTA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

--Secuencia para tabla ECAMEN_PREGUNTA
CREATE SEQUENCE SEQ_EXAMEN_PREGUNTA START WITH 4 INCREMENT BY 1;


--Secuencia para la tabla examen finalizado
CREATE SEQUENCE SEQ_EXAMEN_FINALIZADO START WITH 1 INCREMENT BY 1;

--Secuencia para tabla examenes creados
CREATE SEQUENCE SEQ_HIST_EXAMEN_CREADO START WITH 1 INCREMENT BY 1;

--Secuencia para la tabla de preguntas de bajo rendimiento
CREATE SEQUENCE SEQ_PREGUNTA_BAJO_REND START WITH 1 INCREMENT BY 1;

--Secuencia para la tabla de preguntas modificadas
CREATE SEQUENCE SEQ_MODIF_PREGUNTA START WITH 1 INCREMENT BY 1;

--Secuencia para la tabla hostorial de presentaciones
CREATE SEQUENCE SEQ_HIST_PRESENTACION START WITH 1 INCREMENT BY 1;

-- Secuencia para la tabla resultado esamen del estudiante
CREATE SEQUENCE SEQ_RESULTADO_EXAMEN START WITH 1 INCREMENT BY 1;

-- Verificar las secuencias existentes
-- SELECT SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, LAST_NUMBER FROM USER_SEQUENCES; 