-- Archivo de secuencias para el proyecto Exami

-- Secuencia para la tabla USUARIO (ya existente)
-- CREATE SEQUENCE SEQ_ID_USUARIO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Secuencia para la tabla EXAMEN
CREATE SEQUENCE SEQ_ID_EXAMEN START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Secuencia para la tabla PREGUNTA
CREATE SEQUENCE SEQ_ID_PREGUNTA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Secuencia para la tabla OPCION_RESPUESTA
CREATE SEQUENCE SEQ_ID_OPCION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Secuencia para la tabla EXAMEN_PREGUNTA
CREATE SEQUENCE SEQ_ID_EXAMEN_PREGUNTA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Secuencia para la tabla PRESENTACION_EXAMEN
CREATE SEQUENCE SEQ_ID_PRESENTACION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Secuencia para la tabla RESPUESTA_ESTUDIANTE
CREATE SEQUENCE SEQ_ID_RESPUESTA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Secuencia para la tabla AUDITORIA
CREATE SEQUENCE SEQ_ID_AUDITORIA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Secuencia para la tabla NOTIFICACION
CREATE SEQUENCE SEQ_ID_NOTIFICACION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Verificar las secuencias existentes
-- SELECT SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, LAST_NUMBER FROM USER_SEQUENCES; 