-- Archivo de secuencias para el proyecto Exami

-- Eliminar secuencias existentes
BEGIN
    FOR seq IN (SELECT sequence_name FROM user_sequences) LOOP
        EXECUTE IMMEDIATE 'DROP SEQUENCE ' || seq.sequence_name;
    END LOOP;
END;
/

-- Secuencias para tablas principales
CREATE SEQUENCE SEQ_ID_USUARIO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_ID_FACULTAD
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_ID_PROGRAMA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_ID_CURSO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_ID_PERIODO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_ID_AULA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencias para planificación académica
CREATE SEQUENCE SEQ_ID_PLAN
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_ID_UNIDAD
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_ID_CONTENIDO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_ID_TEMA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencias para grupos y matrículas
CREATE SEQUENCE SEQ_ID_GRUPO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_ID_JORNADA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_ID_MATRICULA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;


-- Secuencias para exámenes y preguntas
CREATE SEQUENCE SEQ_ID_PREGUNTA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_ID_OPCION
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_ID_EXAMEN
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_ID_EXAMEN_PREGUNTA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_ID_PRESENTACION
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_ID_RESPUESTA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencias para catálogos
CREATE SEQUENCE SEQ_ID_TIPO_USUARIO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_ID_TIPO_PREGUNTA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_ID_NIVEL_DIFICULTAD
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_ID_ESTADO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_ID_CATEGORIA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencias para auditoría y notificaciones
CREATE SEQUENCE SEQ_ID_AUDITORIA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_ID_NOTIFICACION
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencias para historiales
CREATE SEQUENCE SEQ_ID_HIST_EXAMEN
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_ID_HIST_PRESENTACION
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_ID_MODIF_PREGUNTA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencias para tablas de rendimiento
CREATE SEQUENCE SEQ_ID_PREGUNTA_BAJO_REND
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_ID_EXAMEN_FINALIZADO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;



-- Secuencias para las tablas de triggers

-- Secuencia para ESTUDIANTES_EXAMEN_FINALIZADO
CREATE SEQUENCE SEQ_EXAMEN_FINALIZADO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencia para HISTORIAL_EXAMENES_CREADOS
CREATE SEQUENCE SEQ_HIST_EXAMEN_CREADO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencia para PREGUNTAS_CON_BAJO_RENDIMIENTO
CREATE SEQUENCE SEQ_PREGUNTA_BAJO_REND
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencia para MODIFICACION_PREGUNTAS
CREATE SEQUENCE SEQ_MODIF_PREGUNTA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencia para HISTORIAL_PRESENTACIONES
CREATE SEQUENCE SEQ_HIST_PRESENTACION
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencia para RESULTADO_EXAMEN_ESTUDIANTE
CREATE SEQUENCE SEQ_RESULTADO_EXAMEN
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;


COMMIT;

-- Verificar las secuencias creadas
SELECT SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, LAST_NUMBER 
FROM USER_SEQUENCES 
ORDER BY SEQUENCE_NAME; 