-- Tabla para almacenar los resultados de los exámenes de los estudiantes
CREATE TABLE RESULTADO_EXAMEN_ESTUDIANTE (
    ID_RESULTADO NUMBER PRIMARY KEY,
    ID_PRESENTACION NUMBER NOT NULL,
    ID_ESTUDIANTE NUMBER NOT NULL,
    ID_EXAMEN NUMBER NOT NULL,
    PUNTAJE_OBTENIDO NUMBER(5,2) NOT NULL,
    UMBRAL_APROBACION NUMBER(5,2) NOT NULL,
    RESULTADO VARCHAR2(10) NOT NULL,
    FECHA_REGISTRO TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_RES_PRESENTACION FOREIGN KEY (ID_PRESENTACION) REFERENCES PRESENTACION_EXAMEN(ID_PRESENTACION),
    CONSTRAINT FK_RES_ESTUDIANTE FOREIGN KEY (ID_ESTUDIANTE) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT FK_RES_EXAMEN FOREIGN KEY (ID_EXAMEN) REFERENCES EXAMEN(ID_EXAMEN),
    CONSTRAINT CHK_RESULTADO CHECK (RESULTADO IN ('APROBADO', 'REPROBADO'))
);

-- Índices para mejorar el rendimiento
CREATE INDEX IDX_RES_ESTUDIANTE ON RESULTADO_EXAMEN_ESTUDIANTE(ID_ESTUDIANTE);
CREATE INDEX IDX_RES_EXAMEN ON RESULTADO_EXAMEN_ESTUDIANTE(ID_EXAMEN);
CREATE INDEX IDX_RES_FECHA ON RESULTADO_EXAMEN_ESTUDIANTE(FECHA_REGISTRO);

-- Comentarios para la tabla y sus columnas
COMMENT ON TABLE RESULTADO_EXAMEN_ESTUDIANTE IS 'Almacena los resultados de los exámenes presentados por los estudiantes';
COMMENT ON COLUMN RESULTADO_EXAMEN_ESTUDIANTE.ID_RESULTADO IS 'Identificador único del resultado';
COMMENT ON COLUMN RESULTADO_EXAMEN_ESTUDIANTE.ID_PRESENTACION IS 'Referencia a la presentación del examen';
COMMENT ON COLUMN RESULTADO_EXAMEN_ESTUDIANTE.ID_ESTUDIANTE IS 'Referencia al estudiante que presentó el examen';
COMMENT ON COLUMN RESULTADO_EXAMEN_ESTUDIANTE.ID_EXAMEN IS 'Referencia al examen presentado';
COMMENT ON COLUMN RESULTADO_EXAMEN_ESTUDIANTE.PUNTAJE_OBTENIDO IS 'Puntaje obtenido por el estudiante';
COMMENT ON COLUMN RESULTADO_EXAMEN_ESTUDIANTE.UMBRAL_APROBACION IS 'Puntaje mínimo necesario para aprobar';
COMMENT ON COLUMN RESULTADO_EXAMEN_ESTUDIANTE.RESULTADO IS 'Estado del resultado (APROBADO/REPROBADO)';
COMMENT ON COLUMN RESULTADO_EXAMEN_ESTUDIANTE.FECHA_REGISTRO IS 'Fecha y hora del registro del resultado';

-- Commit para guardar los cambios
COMMIT; 